<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kelas_Siswa extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('model_kelas_siswa');
        $this->load->library('form_validation');        
	    $this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('admin/list_kelas_siswa');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->model_kelas_siswa->json();
    }

    public function read($id) 
    {
        $row = $this->model_kelas_siswa->get_by_id($id);
        if ($row) {
            $data = array(
            'nis' => $row->nis,
            'id_kelas' => $row->id_kelas
	    );
            $this->load->view('admin/list_kelas_siswa', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('kelas_siswa/create_action'),
            'nis' => set_value('nis'),
            'id_kelas' => set_value('id_kelas')
	);
        $this->load->view('admin/list_kelas_siswa', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data['kelas'] = array();
            $kelas=$this->input->post('id_kelas',TRUE);

            foreach ($kelas as $row) {
                $data["kelas"][]=array('id_kelas'=> $row);
            }

            //Memasukkan data kelas
            $this->model_kelas_siswa->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('admin'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->model_kelas_siswa->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('kelas_siswa/update_action'),
                'nis' => set_value('nis', $row->nis),
                'id_kelas' => set_value('id_kelas', $row->id_kelas),
	    );
            $this->load->view('admin/list_kelas_siswa', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('nis', TRUE));
        } else {
            $data = array();

            $this->model_kelas_siswa->update($this->input->post('nis', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('admin'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->model_kelas_siswa->get_by_id($id);

        if ($row) {
            $this->model_kelas_siswa->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('admin'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin'));
        }
    }

    public function _rules() 
    {

	$this->form_validation->set_rules('nis', 'nis', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Fasilitas_mobil.php */
/* Location: ./application/controllers/Fasilitas_mobil.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-21 02:31:08 */
/* http://harviacode.com */