<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_User extends CI_Model
{

    public $table = 'user';
    public $id = 'id_user';
    public $order = 'DESC';
    public $table_siswa = 'siswa_user';

    function __construct()
    {
        parent::__construct();
        $this->load->model('model_kelas_siswa');
    }

    // datatables
    function json() {
        $this->datatables->select('*');
        $this->datatables->from('user');
        $this->datatables->add_column('action', anchor(site_url('users/read/$1'),'Read')." | ".anchor(site_url('users/update/$1'),'Update')." | ".anchor(site_url('users/delete/$1'),'Delete','onclick="javascript: return confirm(\'Are You Sure ?\')"'), 'id_user');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_siswa()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->where('role', "siswa");
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_user', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('role', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_user', $q);
        $this->db->or_like('username', $q);
        $this->db->or_like('password', $q);
        $this->db->or_like('role', $q);
	    $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data['data']);
        $id=$this->db->insert_id();

        var_dump($data['data']['role']);

        if($data['data']['role']=="siswa"){
            $data['siswa']['id_user']=$id;
            $this->db->insert($this->table_siswa, $data['siswa']);
        }
    }

    // update data
    function update($id, $data)
    {
        //Update tabel user
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data['data']);
        //Update tabel siswa_user
        if ($data['siswa'] && $data['data']['role']==="siswa") {
            //Mengupdate table relasi
            $data['siswa']['id_user'] = $id;
            $this->db->where($this->id, $id)->update($this->table_siswa, $data['siswa']);
        }
    }

    //update user info
    function update_password($id, $data){
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data['new_password']);
    }

    // delete data
    function delete($id)
    {
        //Delete dari tabel siswa_user
        if($this->model_kelas_siswa->get_by_id($id)!=0){
            $this->db->where($this->id, $id);
            $this->db->delete($this->table_siswa);
        }
        //Delete dari tabel user
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Users_model.php */
/* Location: ./application/models/Users_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-21 21:33:47 */
/* http://harviacode.com */